name: Run Twitter Bot

on:
  schedule:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # * is a special character in YAML so quote the string
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *' # Runs Bot every 5 minutes
  # Allow manual triggering of the workflow in the GitHub UI
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        # https://docs.github.com/en/actions/guides/building-and-testing-python#using-a-specific-python-version
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        # https://docs.github.com/en/actions/guides/building-and-testing-python#installing-dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Send Tweet
        run: python tweet.py
        # https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
